### PR TITLE
remove a file that shouldn't be in git

### PR DESCRIPTION
**Pull request by Adimote**
Remove the `.idea/misc.xml` file which has stuff specific to Lloyd's setup.

### CODE REVIEW

**Comment by superdyoll** [comment]
Not sure how that ended up there, I thought most of the personal stuff was in the git ignore. Can you check this file is in the git ignore?

**Comment by Adimote** [comment]
@superdyoll fixed plz approve

**Comment by Adimote** [comment]
actually I'm just merging this

**Comment by Adimote** [comment]
#yolo

**Pull request merged**
